name: Nexus
version: 0.3.0
author: gary600
main: xyz.gary600.nexus.Nexus
api-version: 1.18.1

permissions:
  nexus.class.choose:
    description: Allows choosing one's own class
    default: true

  nexus.class.set:
    description: Allows setting other players' classes
    default: op

  nexus.class.*:
    default: op
    children:
      - nexus.class.choose
      - nexus.class.set

  nexus.configure:
    description: Allows changing configuration, such as enabled worlds
    default: op

  nexus.*:
    default: op
    children:
      - nexus.class.*
      - nexus.configure

commands:
  nexusclass:
    description: Manages your Nexus class
    aliases:
      - class
    usage: /nexusclass choose|get|set|item

  nexus:
    description: Miscellaneous Nexus commands
    usage: /nexus world|debug|reload