name: NexusClasses
version: 0.2.0
author: gary600
main: xyz.gary600.nexusclasses.NexusClasses
api-version: 1.17 # Use latest API

permissions:
  nexusclasses.choose:
    description: Allows choosing one's own class
    default: true

  nexusclasses.set:
    description: Allows setting other players' classes
    default: op

  nexusclasses.configure:
    description: Allows changing configuration, such as enabled worlds
    default: op

  nexusclasses.*:
    description: Wildcard permission
    default: op
    children:
      - nexusclasses.choose
      - nexusclasses.set
      - nexusclasses.configure

commands:
  nexusclass:
    description: foo
    aliases:
      - class
    usage: /nexusclass choose|get|set|item|world