name: Nexus
version: 0.3.1
author: gary600
main: xyz.gary600.nexus.Nexus
api-version: 1.19

permissions:
  nexus.classes.choose:
    description: Allows choosing one's own class
    default: true

  nexus.classes.set:
    description: Allows setting other players' classes
    default: op

  nexus.classes.*:
    default: op
    children:
      - nexus.classes.choose
      - nexus.classes.set

  nexus.configure:
    description: Allows changing configuration, such as enabled worlds
    default: op

  nexus.*:
    default: op
    children:
      - nexus.classes.*
      - nexus.configure

commands:
  nexusclass:
    description: Manages your Nexus class
    aliases:
      - class
    usage: /nexusclass choose|get|set|item

  nexus:
    description: Miscellaneous Nexus commands
    usage: /nexus world|debug|reload