name: Build Nexus (FIXME)
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch source
        uses: actions/checkout@v2
      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew shadowJar
      - name: Upload jar as artifact
        uses: actions/upload-artifact@v2
        with:
          name: plugin-jar
          path: build/libs/Nexus*.jar